#include "common.h"
#include "gol_texture.h"

#include "render/gol_render_device.h"

// Large scene/world struct passed as arg2 to vfunc16
struct BunyipScene {
    /* 0x00 */ u8 pad00[0x40];
    /* 0x40 */ s32 unk40;
    /* 0x44 */ s32 unk44;
    /* 0x48 */ u8 pad48[4];
    /* 0x4C */ GolSurfaceFormat pixelFormat;
    /* 0x64 */ u8 pad64[0x38];
    /* 0x9C */ BunyipMark unk9C;
    /* 0xA0 */ u8 padA0[0x50C];
    /* 0x5AC = vptr */

    virtual UNK v1(UNK) = 0;
    virtual UNK v2(UNK) = 0;
    virtual UNK v3(UNK) = 0;
    virtual UNK v4(UNK) = 0;
    virtual UNK v5(UNK) = 0;
    virtual void vfunc6(GolTexture* self, s32 flag, BunyipMark* mark) = 0;
};

extern "C" const BunyipMark D_80002430 = { { 0, 0, 0, 0 } };

void GolTexture::vfunc16(GolRenderDevice* ctx, BunyipScene* arg2) {
    GolSurfaceFormat pf1;
    GolSurfaceFormat pf2;

    pf1 = arg2->pixelFormat;

    if (ctx->vfunc68()) {
        flags |= 0x40;
    }

    u16 fl = flags;
    if ((fl & 0x20) && (ctx->flags & 0x200)) {
        flags = fl | 0x80;
    }

    ctx->vfunc4(&pf1, &pf2, flags & 0x20);

    s32 a40 = arg2->unk40;
    s32 a44 = arg2->unk44;
    vfunc14(ctx, &pf2, a40, a44);

    u16 fl2 = flags;
    if (fl2 & 0x20) {
        BunyipMark mark;
        mark = unk30;

        if (ctx->flags & 0x200) {
            arg2->unk9C = D_80002430;
        } else {
            arg2->unk9C = mark;
        }

        arg2->vfunc6(this, flags & 0x4, &mark);
    } else {
        arg2->vfunc6(this, fl2 & 0x4, NULL);
    }
}

GolTexture::GolTexture() {
    unk34 = 0;
    flags = 0;
}

void GolTexture::func_80029194(u16 val) {
    unk34 = val;
}

u16 GolTexture::func_8002919C() {
    return flags;
}

void GolTexture::func_800291A8(u16 val) {
    flags = val;
}

void GolTexture::func_800291B0(BunyipTrack* dst) {
    *dst = unk38;
}

void GolTexture::func_800291D8(BunyipTrack* src) {
    unk38 = *src;
}

void GolTexture::func_80029200(BunyipMark* dst) {
    *dst = unk30;
}

void GolTexture::func_80029218(BunyipMark* src) {
    unk30 = *src;
    unk30.data[3] = 0;
    flags |= 0x800;
}

u16 GolTexture::func_8002923C() {
    return flags & 0x1000;
}

u16 GolTexture::func_80029248() {
    return flags & 0x20;
}

u16 GolTexture::func_80029254() {
    return flags & 0x10;
}

u16 GolTexture::func_80029260() {
    return flags & 0x8;
}

u16 GolTexture::func_8002926C() {
    return flags & 0x200;
}

u16 GolTexture::func_80029278() {
    return flags & 0x100;
}

u16 GolTexture::func_80029284() {
    return flags & 0x4;
}

u16 GolTexture::func_80029290() {
    return flags & 0x2;
}

u16 GolTexture::func_8002929C() {
    return flags & 0x1;
}

u16 GolTexture::func_800292A8() {
    return unk34;
}

// vtable generated by compiler
